version: 0.2

# env:
#     variables:
        # CACHE_CONTROL: "86400"
        # S3_BUCKET: "{{s3_bucket_url}}"
        # BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - rm package-lock.json
  build:
    commands:
        - echo Build started 
        - ng build
        - ls -l -F
artifacts:
    files:
        - '**/*'
    base-directory: dist/maguires-ms
    discard-paths: no

    # This build script worked from this tutorial::: https://www.youtube.com/watch?v=i8NyeqSc4GI

    # Ubuntu standard 5